# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/claimdb',
                'doc_host': 'https://claimdb.github.io',
                'git_url': 'https://github.com/claimdb/claimdb',
                'lib_path': 'claimdb'},
  'syms': {'claimdb.core': {'claimdb.core.foo': ('core.html#foo', 'claimdb/core.py')}}}
