"""Config"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_configuration.ipynb.

# %% auto #0
__all__ = ['config', 'Config']

# %% ../nbs/01_configuration.ipynb #6a9314a8
from pathlib import Path
from dotenv import set_key, load_dotenv, dotenv_values
import claimdb

# %% ../nbs/01_configuration.ipynb #845a017b
class Config:
    
    DEFAULTS = {
        "MODEL": "gpt-5",
    }
    
    def __init__(self):
        # Path Configs
        self.project_root = Path(claimdb.__file__).parent.parent

        self.original_data_dir = self.project_root / "original-data"
        self.bird_dir = self.original_data_dir / "BIRD"
        self.bird_databases_dir = self.bird_dir / "databases"

        self.output_data_dir = self.project_root / "output-data"

        self.experiments_dir = self.project_root / "experiments"
        self.experiments_dir_priv = self.experiments_dir / "private"
        self.experiments_dir_pub = self.experiments_dir / "public"
        self.experiments_log_dir = self.experiments_dir / "logs"

        self.filter_data_dir = self.project_root / "filter-data"
        self.embeddings_dir = self.filter_data_dir / "embeddings"
        self.judges_dir = self.filter_data_dir / "judges"

        self.paper_plots_dir = self.project_root / "paper-plots"

        self.final_benchmark_dir = self.project_root / "final-benchmark"

        self.env_path = self.project_root / ".env"
        self.env_path.touch(exist_ok=True)

        # Set defaults if not already set
        env = dotenv_values(self.env_path)
        for key, val in self.DEFAULTS.items():
            if key not in env:
                self.set_env_var(key, str(val))

        # Load environment variables
        self._load_env()

    def _load_env(self):
        """Load everything in DEFAULTS + everything in the .env file."""
        # Load into the environment to make sure
        load_dotenv(self.env_path, override=True)
        env = dotenv_values(self.env_path)

        for key, val in env.items():
            if val.isdigit(): setattr(self, key.lower(), int(val))
            else: setattr(self, key.lower(), val)
    
    def restore_defaults(self):
        for key, val in self.DEFAULTS.items():
            self.set_env_var(key, str(val))

    def set_env_var(self, key, value):
        """Set or update a variable and persist to .env."""
        set_key(self.env_path, key, str(value))
        self._load_env()

    def show_config(self, scramble=None):
        env = dotenv_values(self.env_path)
        for key, val in env.items():
            
            if scramble: 
                if key in scramble: print(f"{key}=XXYYZZ")
                else: print(f"{key}={val}")
            else:
                print(f"{key}={val}")

# %% ../nbs/01_configuration.ipynb #f9ec4618
config = Config()
