"""In this notebook we will filter out overly outrageous claims (i.e., claims that are obviously out of the schema)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05b_filter_similarity.ipynb.

# %% auto #0
__all__ = ['create_compact_answer']

# %% ../nbs/05b_filter_similarity.ipynb #a2c93e1e
from .preprocess_bird import *
from .configuration import *
import json

# %% ../nbs/05b_filter_similarity.ipynb #d777e066
with open(config.bird_dir / 'train_dev_filtered.jsonl', 'r') as f:
    bird_data = [json.loads(line) for line in f.readlines()]

# %% ../nbs/05b_filter_similarity.ipynb #d71c768b
import numbers

# %% ../nbs/05b_filter_similarity.ipynb #0c40c008
def create_compact_answer(answer_dict):

    rows = []
    for d in answer_dict:

        values = []
        for v in d.values():
            if isinstance(v, numbers.Number):
                v = f"{float(v):.3f}"
            values.append(str(v))

        rows.append(', '.join(values))

    compact_answer = '; '.join(rows)
    return compact_answer
