"""Here, we load, process, and transform the bird benchmark."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_preprocess_bird.ipynb.

# %% auto #0
__all__ = ['load_bird_table_description', 'load_bird_database_schema', 'format_for_llm', 'convert_db_name',
           'prepare_bird_example']

# %% ../nbs/03_preprocess_bird.ipynb #21e6ae64
import json
from .configuration import *
from .dbops import *

# %% ../nbs/03_preprocess_bird.ipynb #8328d412
import pandas as pd
from pathlib import Path

# %% ../nbs/03_preprocess_bird.ipynb #76e26dad
def load_bird_table_description(csv_path: Path) -> str:
    """Load a single table description from BIRD CSV format as compact text."""
    df = pd.read_csv(csv_path)
    
    table_name = csv_path.stem  # e.g., "Air Carriers"
    
    lines = [f"Table: {table_name}"]
    lines.append("Columns:")
    
    for _, row in df.iterrows():
        col_name = row['column_name'] if pd.notna(row['column_name']) else row['original_column_name']

        # Build compact column line
        col_line = f"  - {col_name}"
        
        lines.append(col_line)
    
    return '\n'.join(lines)

# %% ../nbs/03_preprocess_bird.ipynb #f4a1acd5
def load_bird_database_schema(db_path: Path) -> str:
    """Load all table descriptions for a BIRD database as compact text."""
    desc_dir = db_path / 'database_description'
    
    if not desc_dir.exists():
        return None
    
    tables = []
    for csv_file in desc_dir.glob('*.csv'):
        table_info = load_bird_table_description(csv_file)
        tables.append(table_info)
    
    return '\n\n'.join(tables)

# %% ../nbs/03_preprocess_bird.ipynb #1428edcb
def format_for_llm(d):
    """Format database schema as JSON for LLMs that prefer structured input."""
    return json.dumps(d, ensure_ascii=False, indent=2)

# %% ../nbs/03_preprocess_bird.ipynb #5c09b96e
def convert_db_name(db_id): # The database ID (e.g., 'world_1')
    """ Converts a database ID to a more human-readable format. """
    return db_id.replace('_', ' ').title()

# %% ../nbs/03_preprocess_bird.ipynb #8f462f95
def prepare_bird_example(example: dict, with_schema: bool = False):
    d = {
        'question': example['question'],
        'answer': example['result'],
        'domain': convert_db_name(example['db_id']),
        'external-knowledge': example['evidence']
    }

    if with_schema:
        d['db-schema'] = example['db-schema']

    return d
