"""Here, we see experiment results!"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_visualize.ipynb.

# %% auto #0
__all__ = ['models', 'info_dict', 'load_df']

# %% ../nbs/08_visualize.ipynb #601a4389
import json
from .configuration import config

# %% ../nbs/08_visualize.ipynb #f657a9ba
with open(config.output_data_dir / 'all_claims_judged.jsonl', "r") as f:
    all_claims = [json.loads(line) for line in f]

    claim_map = {
        item['claim_id']: item for item in all_claims
    }

# %% ../nbs/08_visualize.ipynb #10bab8b4
def load_df(model_name, path=None):
    predicted_results = []

    if path: p = path
    else: p = config.experiments_dir_pub / f"{model_name}.jsonl"

    with open(p, "r") as f:
        for line in f:

            log = json.loads(line)
            claim_id = log['claim_id']
            if claim_id not in claim_map: continue
            verdict = log['verdict']

            category = claim_map[claim_id].get('category', None)
            ground_truth = claim_map[claim_id]['label']
            db_name = claim_map[claim_id]['db_name']

            # Tool Calls
            num_tool_calls = None
            
            if "model_settings" in log and  not "error" in log:  # Means we are in OpenAI's SDK
                num_tool_calls = 0
                for item in log['to_input_list']:
                    if item.get('type', None) == 'function_call':
                        num_tool_calls += 1

            if "model_settings" not in log and not "error" in log:  # Means we are in Pydantic's Agents
                if log.get("error", None): 
                    num_tool_calls = None
                    continue
                num_tool_calls = 0
                for message in log.get('all_messages', []):
                    # Check if this is a response message
                    if message.get('kind') == 'response':
                        # Look through the parts for tool calls
                        for part in message.get('parts', []):
                            if part.get('part_kind') == 'tool-call':
                                num_tool_calls += 1

            entry = {
                'claim_id': claim_id,
                'verdict': verdict,
                'ground_truth': ground_truth,
                'category': category,
                'db_name': db_name,
                'tool_calls': num_tool_calls
            }

            predicted_results.append(entry)
    
    df = pd.DataFrame(predicted_results)
    df['correct'] = df['verdict'] == df['ground_truth']

    return df

# %% ../nbs/08_visualize.ipynb #bbccf4f4
models = [
    'gpt-4o-mini',
    'gpt-4.1-nano',
    'gpt-5-nano',
    'gpt-5-mini',
    'gpt-oss:20b',
    'gemini-2.5-flash',
    'gemini-3-flash-preview',
    'claude-3-haiku-20240307',
    'claude-3-5-haiku-20241022',
    'claude-haiku-4-5',
    'qwen3:1.7b',
    'qwen3:4b',
    'qwen3:8b',
    'qwen3:14b',
    'qwen3:32b',
    'qwen3-coder:30b',
    'ministral-3:3b',
    'ministral-3:8b',
    'ministral-3:14b',
    'mistral-nemo:12b',
    'mistral-small:22b',
    'magistral:24b',
    'devstral:24b',
    'devstral-small-2:24b',
    'nemotron-3-nano:30b',
    'llama3.1:8b',
    'llama3.2:3b',
    'cogito:14b',
    'cogito:32b',
    'qwq:32b',
]

info_dict = {
    'gpt-4o-mini': {'name': 'gpt-4o-mini', 'params': None, 'creator': 'OpenAI'},
    'gpt-4.1-nano': {'name': 'gpt-4.1-nano', 'params': None, 'creator': 'OpenAI'},
    'gpt-5-nano': {'name': 'gpt-4.1-nano', 'params': None, 'creator': 'OpenAI'},
    'gpt-5-mini': {'name': 'gpt-5-mini', 'params': None, 'creator': 'OpenAI'},
    'gpt-oss:20b': {'name': 'gpt-oss', 'params': 20, 'creator': 'OpenAI'},
    'gemini-2.5-flash': {'name': 'gemini-2.5-flash', 'params': None, 'creator': 'Google'},
    'gemini-3-flash-preview': {'name': 'gemini-3-flash', 'params': None, 'creator': 'Google'},
    'claude-3-haiku-20240307': {'name': 'claude-3-haiku', 'params': None, 'creator': 'Anthropic'},
    'claude-3-5-haiku-20241022': {'name': 'claude-3-5-haiku', 'params': None, 'creator': 'Anthropic'},
    'claude-haiku-4-5': {'name': 'claude-haiku-4-5', 'params': None, 'creator': 'Anthropic'},
    'qwen3:1.7b': {'name': 'qwen3', 'params': 1.7, 'creator': 'Alibaba'},
    'qwen3:4b': {'name': 'qwen3', 'params': 4, 'creator': 'Alibaba'},
    'qwen3:8b': {'name': 'qwen3', 'params': 8, 'creator': 'Alibaba'},
    'qwen3:14b': {'name': 'qwen3', 'params': 14, 'creator': 'Alibaba'},
    'qwen3:32b': {'name': 'qwen3', 'params': 32, 'creator': 'Alibaba'},
    'qwen3-coder:30b': {'name': 'qwen3-coder', 'params': 30, 'creator': 'Alibaba'},
    'ministral-3:3b': {'name': 'ministral-3', 'params': 3, 'creator': 'Mistral AI'},
    'ministral-3:8b': {'name': 'ministral-3', 'params': 8 , 'creator': 'Mistral AI'},
    'ministral-3:14b': {'name': 'ministral-3', 'params': 14, 'creator': 'Mistral AI'},
    'mistral-small:22b': {'name': 'mistral-small', 'params': 22, 'creator': 'Mistral AI'},
    'magistral:24b': {'name': 'magistral', 'params': 24, 'creator': 'Mistral AI'},
    'mistral-nemo:12b': {'name': 'mistral-nemo', 'params': 12, 'creator': 'Mistral AI'},
    'devstral:24b': {'name': 'devstral', 'params': 24, 'creator': 'Mistral AI'},
    'devstral-small-2:24b': {'name': 'devstral-small-2', 'params': 24, 'creator': 'Mistral AI'},
    'nemotron-3-nano:30b': {'name': 'nemotron-3-nano', 'params': 30, 'creator': 'NVIDIA'},
    'llama3.1:8b': {'name': 'llama3.1', 'params': 8, 'creator': 'Meta'},
    'llama3.2:3b': {'name': 'llama3.2', 'params': 3, 'creator': 'Meta'},
    'cogito:14b': {'name': 'cogito', 'params': 14, 'creator': 'Deep Cogito'},
    'cogito:32b': {'name': 'cogito', 'params': 32, 'creator': 'Deep Cogito'},
    'qwq:32b': {'name': 'qwq', 'params': 32, 'creator': 'Alibaba'},
}

for model_name, dictionary in info_dict.items():
    if dictionary['params'] is not None:
        extra = f" ({dictionary['params']}B)"
    else:
        extra = ''
    dictionary['display_name_p'] = f"{dictionary['name']}{extra}"
