"""Here, we see experiment results!"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_visualize.ipynb.

# %% auto #0
__all__ = ['models', 'info_dict']

# %% ../nbs/08_visualize.ipynb #e797dfba
with open(config.output_data_dir / 'all_claims_judged.jsonl', "r") as f:
    all_claims = [json.loads(line) for line in f]

    claim_map = {
        item['claim_id']: item for item in all_claims
    }

# %% ../nbs/08_visualize.ipynb #823fdbef
models = [
    'gpt-4o-mini',
    'gpt-4.1-nano',
    'gpt-5-nano',
    'gpt-5-mini',
    'gpt-oss:20b',
    'gemini-2.5-flash',
    'gemini-3-flash-preview',
    'claude-3-haiku-20240307',
    'claude-3-5-haiku-20241022',
    'claude-haiku-4-5',
    'qwen3:1.7b',
    'qwen3:4b',
    'qwen3:8b',
    'qwen3:14b',
    'qwen3:32b',
    'qwen3-coder:30b',
    'ministral-3:3b',
    'ministral-3:8b',
    'ministral-3:14b',
    'mistral-nemo:12b',
    'mistral-small:22b',
    'magistral:24b',
    'devstral:24b',
    'devstral-small-2:24b',
    'nemotron-3-nano:30b',
    'llama3.1:8b',
    'llama3.2:3b',
    'cogito:14b',
    'cogito:32b',
    'qwq:32b',
]

info_dict = {
    'gpt-4o-mini': {'name': 'gpt-4o-mini', 'params': None, 'creator': 'OpenAI'},
    'gpt-4.1-nano': {'name': 'gpt-4.1-nano', 'params': None, 'creator': 'OpenAI'},
    'gpt-5-nano': {'name': 'gpt-5-nano', 'params': None, 'creator': 'OpenAI'},
    'gpt-5-mini': {'name': 'gpt-5-mini', 'params': None, 'creator': 'OpenAI'},
    'gpt-oss:20b': {'name': 'gpt-oss', 'params': 20, 'creator': 'OpenAI'},
    'gemini-2.5-flash': {'name': 'gemini-2.5-flash', 'params': None, 'creator': 'Google'},
    'gemini-3-flash-preview': {'name': 'gemini-3-flash', 'params': None, 'creator': 'Google'},
    'claude-3-haiku-20240307': {'name': 'claude-3-haiku', 'params': None, 'creator': 'Anthropic'},
    'claude-3-5-haiku-20241022': {'name': 'claude-3-5-haiku', 'params': None, 'creator': 'Anthropic'},
    'claude-haiku-4-5': {'name': 'claude-haiku-4-5', 'params': None, 'creator': 'Anthropic'},
    'qwen3:1.7b': {'name': 'qwen3', 'params': 1.7, 'creator': 'Alibaba'},
    'qwen3:4b': {'name': 'qwen3', 'params': 4, 'creator': 'Alibaba'},
    'qwen3:8b': {'name': 'qwen3', 'params': 8, 'creator': 'Alibaba'},
    'qwen3:14b': {'name': 'qwen3', 'params': 14, 'creator': 'Alibaba'},
    'qwen3:32b': {'name': 'qwen3', 'params': 32, 'creator': 'Alibaba'},
    'qwen3-coder:30b': {'name': 'qwen3-coder', 'params': 30, 'creator': 'Alibaba'},
    'ministral-3:3b': {'name': 'ministral-3', 'params': 3, 'creator': 'Mistral AI'},
    'ministral-3:8b': {'name': 'ministral-3', 'params': 8 , 'creator': 'Mistral AI'},
    'ministral-3:14b': {'name': 'ministral-3', 'params': 14, 'creator': 'Mistral AI'},
    'mistral-small:22b': {'name': 'mistral-small', 'params': 22, 'creator': 'Mistral AI'},
    'magistral:24b': {'name': 'magistral', 'params': 24, 'creator': 'Mistral AI'},
    'mistral-nemo:12b': {'name': 'mistral-nemo', 'params': 12, 'creator': 'Mistral AI'},
    'devstral:24b': {'name': 'devstral', 'params': 24, 'creator': 'Mistral AI'},
    'devstral-small-2:24b': {'name': 'devstral-small-2', 'params': 24, 'creator': 'Mistral AI'},
    'nemotron-3-nano:30b': {'name': 'nemotron-3-nano', 'params': 30, 'creator': 'NVIDIA'},
    'llama3.1:8b': {'name': 'llama3.1', 'params': 8, 'creator': 'Meta'},
    'llama3.2:3b': {'name': 'llama3.2', 'params': 3, 'creator': 'Meta'},
    'cogito:14b': {'name': 'cogito', 'params': 14, 'creator': 'Deep Cogito'},
    'cogito:32b': {'name': 'cogito', 'params': 32, 'creator': 'Deep Cogito'},
    'qwq:32b': {'name': 'qwq', 'params': 32, 'creator': 'Alibaba'},
}

for model_name, dictionary in info_dict.items():
    if dictionary['params'] is not None:
        extra = f" ({dictionary['params']}B)"
    else:
        extra = ''
    dictionary['display_name_p'] = f"{dictionary['name']}{extra}"
