"""Here, we see experiment results!"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_visualize.ipynb.

# %% auto #0
__all__ = ['load_df']

# %% ../nbs/08_visualize.ipynb #601a4389
import json
from dbverify.configuration import config

# %% ../nbs/08_visualize.ipynb #f657a9ba
with open(config.output_data_dir / 'all_claims_judged.jsonl', "r") as f:
    all_claims = [json.loads(line) for line in f]

    claim_map = {
        item['claim_id']: item for item in all_claims
    }

# %% ../nbs/08_visualize.ipynb #10bab8b4
def load_df(model_name, path=None):
    predicted_results = []

    if path: p = path
    else: p = config.experiments_dir_pub / f"{model_name}.jsonl"

    with open(p, "r") as f:
        for line in f:

            log = json.loads(line)
            claim_id = log['claim_id']
            if claim_id not in claim_map: continue
            verdict = log['verdict']

            category = claim_map[claim_id].get('category', None)
            ground_truth = claim_map[claim_id]['label']
            db_name = claim_map[claim_id]['db_name']

            # Tool Calls
            num_tool_calls = None
            
            if "model_settings" in log and  not "error" in log:  # Means we are in OpenAI's SDK
                num_tool_calls = 0
                for item in log['to_input_list']:
                    if item.get('type', None) == 'function_call':
                        num_tool_calls += 1

            if "model_settings" not in log and not "error" in log:  # Means we are in Pydantic's Agents
                if log.get("error", None): 
                    num_tool_calls = None
                    continue
                num_tool_calls = 0
                for message in log.get('all_messages', []):
                    # Check if this is a response message
                    if message.get('kind') == 'response':
                        # Look through the parts for tool calls
                        for part in message.get('parts', []):
                            if part.get('part_kind') == 'tool-call':
                                num_tool_calls += 1

            entry = {
                'claim_id': claim_id,
                'verdict': verdict,
                'ground_truth': ground_truth,
                'category': category,
                'db_name': db_name,
                'tool_calls': num_tool_calls
            }

            predicted_results.append(entry)
    
    df = pd.DataFrame(predicted_results)
    df['correct'] = df['verdict'] == df['ground_truth']

    return df
